### ISSUE TITLE
Implement Frontend example for abm output object

### ISSUE THREAD

**Issue by jubicker** [SciCompMod/memilio#635]
### Motivation / Current Behaviour

To test the abm output object we need to implement an example output.

### Enhancement description

The output should be a txt file and have one line per location. It should contain the following columns:

- location Id
- number of output timesteps
- timestep 1 (t1)
- number of agents in location in t1
- agent id 1 (a1)
- time since transmission for a1
- agent id 2 (a2)
- time since transmission for a2
- ...
- timestep 2 (t2)
- number of agents in location in t2
- agent id 1
- time since transmission for a1
- agent id 2
- time since transmission for a2
- ...
- timestep 3 (t3)
- ...

As we need the time since transmission for every agent at every timestep, this has to be added as an attribute to the person class. For agents that are not infected this should be set to -1 in the txt file.

### Checklist

- [X] Attached labels, especially loc:: or model:: labels.
- [X] Linked to project

**Comment by xsaschako** [comment]
This issue will also be handling the output object for frontend ESID

**Comment by xsaschako** [comment]
This issue will just handle the example for the frontend. 
The example for the Demonstrator will be done in #604

**Comment by xsaschako** [comment]
As per Discussion with Moritz:

# ABM Object 23-07-12

#Revisit  
Participants: [[Sascha Korf (DLR-SC-HPC)]]
Tags: [[PANDEMOS]]

---
- no progress due to vacations
  - will be worked on this week
- probably hdf5 files (but open in theory)

Data contained in Output (for single run):
- Locations Lookup
  | Field      | Description                             |
  |------------|-----------------------------------------|
  | LocationID | ID used in the movement vectors         |
  | Latitude   | Latitude of the location's coordinates  |
  | Longitude  | Longitude of the location's coordinates |

- Agent Lookup(?)
  | Field    | Description                                                                               |
  |----------|-------------------------------------------------------------------------------------------|
  | AgentID  | ID of the Agent                                                                           |
  | (HomeID) | Location ID of the Agents home/household                                                  |
  | Groups   | List of stratification groups (socio-economic) the Agent belongs to (i.e. age16-30, male) | 

- Movement Data
  | Field          | Description                                                                           |
  |----------------|---------------------------------------------------------------------------------------|
  | TripID         | ID of the trip/movement vector                                                        |
  | AgentID        | ID of the Agent doing the trip                                                        |
  | (HomeID)       | ID of the Household (or Location ID of the agents home?)                              |
  |                |                                                                                       |
  | StartLocation  | Location ID of the start                                                              |
  | EndLocation    | Location ID of the end                                                                |
  |                |                                                                                       |
  | StartTime      | Timestamp of the start                                                                |
  | EndTime        | Timestamp of the end                                                                  |
  |                |                                                                                       |
  | TransportMode  | mode of transportation                                                                |
  | Activity       | Activity at the end (reason for trip)                                                 |
  | InfectionState | Compartment(s) the Agent belongs to while on trip (infected, naive vaccination, etc.) |

---

Related:
