### ISSUE TITLE
Inconsistent data from getCaseData.py

### ISSUE THREAD

**Issue by LSchueler** [SciCompMod/memilio#796]
### Bug description

I'm using the `getCaseData.py` script to download and prepare the RKI data. When checking the results I found some inconsistencies between different levels of data granularity, e.g. all aggregated cases for a county vs. cases divided in gender for a county vs. cases divided in age classes for a county. This seems to happen on county level, state level, and national level.

Here are a few examples of mismatches:

**county level**

`cases_all_county.json`
date: 2020-04-24
ID_County: 1002
confirmed: 263
deaths: 10
recov.: 253

`cases_all_county_gender.json` for the same date and county matches the above values.

`cases_all_county_age.json`
date: 2020-04-24
ID_County: 1002
Age_RKI: 15-34
confirmed: 82
deaths: 0
recov.: 82

date: 2020-04-24
ID_County: 1002
Age_RKI: 60-79
confirmed: 66
deaths: 6
recov.: 60

**state level**

`cases_all_state.json`
date: 2020-04-24
ID_State: 1
confirmed: 2725
deaths: 139
recovered: 2586

`cases_all_state_age.json`
date: 2020-04-24
ID_State: 1
RKI_Age: 15-34
confirmed: 641
deaths: 0
recovered: 641

date: 2020-04-24
ID_State: 1
RKI_Age: 35-59
confirmed: 1122
deaths: 9
recovered: 1113

date: 2020-04-24
ID_State: 1
RKI_Age: 60-79
confirmed: 589
deaths: 52
recovered: 537

date: 2020-04-24
ID_State: 1
RKI_Age: 80+
confirmed: 305
deaths: 78
recovered: 227

`cases_all_state_gender.json`
date: 2020-04-24
ID_State: 1
gender: female
confirmed: 1478
deaths: 54
recovered: 1424

date: 2020-04-24
ID_State: 1
gender: male
confirmed: 1247
deaths: 85
recovered: 1162

**national level**

`cases_all_germany.json`
confirmed: 159200
deaths: 8270
recovered: 150983

`cases_all_gender.json`
gender: female
confirmed: 83266
deaths: 3626
recovered: 79640

gender: male
confirmed: 75806
deaths: 4588
recovered: 71217

and so on.

### Version

Linux

### To reproduce

1. for `getCaseData.py` change values of `arg_dict` (which are either taken from `defaultDict.defaultDict` or from the cli) to
`{'start_date': date(2020, 4, 24), 'end_date': date(2020, 5, 5)}` (changing `impute_dates` does not change the behaviour)
2. execute `getCaseData.py`
3. check outputs like `cases_all_county.json` vs. `cases_all_county_age.json` vs. `cases_all_county_gender.json` or `cases_all_germany.json` vs. `cases_all_gender.json` vs. `cases_all_age.json` etc.

### Checklist

- [x] Attached labels, especially loc:: or model:: labels.
- [x] Linked to project

**Comment by mknaranja** [comment]
Yes. Thanks @LSchueler. As promised, I will look at this tomorrow morning.

**Comment by mknaranja** [comment]
Hi @LSchueler,

the problem is much less critical than it seemed it it is in fact as I assumed yesterday (but I still had forgotten about one important point). I think we have to rewrite the script but it is also a conceptual question on how to rewrite it. Please look at the discussion at the end of my posting. First let me confirm the following:

```
county level
cases_all_county.json
date: 2020-04-24
ID_County: 1002
confirmed: 263 --> validated with data from 2021/2022 (vacc paper) and current initial data frame
deaths: 10 --> validated with data from 2021/2022 (vacc paper) and current initial data frame
recov.: 253 --> validated with data from 2021/2022 (vacc paper) and current initial data frame
cases_all_county_gender.json for the same date and county matches the above values.
cases_all_county_age.json
date: 2020-04-24
ID_County: 1002
Age_RKI: 15-34
confirmed: 82 -> validated with data from 2021/2022 (vacc paper) and current initial data frame
deaths: 0
recov.: 82  -> validated with data from 2021/2022 (vacc paper) and current initial data frame
date: 2020-04-24
ID_County: 1002
Age_RKI: 60-79
confirmed: 66 --> validated with data from 2021/2022 (vacc paper) and current initial data frame
deaths: 6
recov.: 60 --> validated with data from 2021/2022 (vacc paper) and current initial data frame

Missing confirmed cases:
0-4: 0
5-14: 2 <-- appear on 2020/04/14 in cases_all_county_age.json if start_date is 2020/01/01
35-59: 90 <-- appear on 2020/04/22 in cases_all_county_age.json if start_date is 2020/01/01
80+: 23 <-- appear on 2020/04/20 in cases_all_county_age.json if start_date is 2020/01/01
```

The problem is the following:

- In [line 335-339 ](https://github.com/DLR-SC/memilio/blob/aaacb237c5591425b5f5480c58569b7756d2c157/pycode/memilio-epidata/memilio/epidata/getCaseData.py#L335-L346), we compute the cumulative sum of the confirmed cases, deaths, recoveries. Until here, always the full data frame from January 1, 2020 is considered and no missing dates were imputed.
- If there was a confirmation for a certain age group/gender *and* a certain date, we get an accumulated number for an age group/gender *and* that date. Otherwise not.
- Then, we call [`impute_and_reduce_df()`](https://github.com/DLR-SC/memilio/blob/aaacb237c5591425b5f5480c58569b7756d2c157/pycode/memilio-epidata/memilio/epidata/getCaseData.py#L335-L346) which first removes all entries before the start date and then imputes the last seen value for all combinations of age/gender and e.g., a particular county. However, the cumulative sum for entries which did not happen on the start date are removed and it starts with zero.

The difference in the total numbers for 2021-2023 is small if you start with `start_date` 2020/04/24 but there a still small errors.

The current workaround is to always start with `start_date` 2020/01/01.

There are two fundamentally different ways in 'correcting' this. The question is what `start_date` and `end_date` should mean:
1. Give me the accumulated numbers between start and end *from the beginning of the pandemic*
2. Give me the accumulated numbers *only* between start and end

Actually, we never really used `start_date` and `end_date` so far. It was just my idea to let users select a subframe which then never was used. And unfortunately it was not correctly implemented or incomplete. To my understanding, the second option above is the more reasonable to give if you provide start and end, don't you agree?

**Comment by LSchueler** [comment]
Hi @mknaranja ,

pheow, that's a relief! And thank you for the very quick response. I can confirm that the numbers now all add up, if I use 2020-01-01 for `start_date`.

I don't have a very strong opinion on which way this should be corrected. I could however imagine that it would be more confusing if the cumulative numbers depend on the `start_date`. And is there actually an application for the case that you want the cumulative numbers only from a certain date onward?
By the way, a third option would be to drop the `start_date` argument all together ;-)

Thanks again!

**Comment by mknaranja** [comment]
I think the "problem" is the cumulative sum. If we just provided reported daily cases, then one would not expect to have the data before `start_date` included. 

I think it is possible that one is only interested in the data in the time frame `end-start` but that could also be recomputed from the cumulative sum by subtracting the start values from the end values.

I would not drop the start_date, if we use moving average or imputation, it is a computational reduction (time and disk space) to not include all dates.

**Comment by HenrZu** [comment]
I will discuss this together with @patricklnz. From my first look, i would second your opinion not to drop the start_date argument and prefer to recompute the the results before returning output. 
Fortunately, the solution seems to be much easier than I thought at first :)
We will provide a solution early next week.

**Comment by annawendler** [comment]
When using getVaccinationData.py to get the vaccination data we also get different results depending on `start_date`. I suspect this is a similar issue.
